# Generated by Django 5.0.7 on 2024-07-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeBreakfastImages',
            new_name='HomeBreakfastImage',
        ),
        migrations.RenameModel(
            old_name='HomeRoomImages',
            new_name='HomeRoomImage',
        ),
        migrations.RenameModel(
            old_name='HomeTourImages',
            new_name='HomeTourImage',
        ),
    ]
