# Generated by Django 5.0.7 on 2024-07-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_homebreakfastimages_homebreakfastimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
