# Generated by Django 5.0.7 on 2024-07-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gallerymodel_rename_homepage_homemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='title',
            field=models.CharField(default='imagen', max_length=20),
            preserve_default=False,
        ),
    ]
