# Generated by Django 5.0.7 on 2024-07-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subscriptionmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerymodel',
            options={'verbose_name': 'Gallery Page', 'verbose_name_plural': 'Gallery Page'},
        ),
        migrations.AlterModelOptions(
            name='homemodel',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Page'},
        ),
        migrations.AlterModelOptions(
            name='introductionmodel',
            options={'verbose_name': 'Introduction Page', 'verbose_name_plural': 'Introduction Page'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionmodel',
            options={'verbose_name': 'Subscription Emails', 'verbose_name_plural': 'Subscription Emails'},
        ),
        migrations.AddField(
            model_name='homemodel',
            name='subtitle_banner_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='subtitle_banner_es',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_banner_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='title_banner_es',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='subtitle_banner',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='title_banner',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='welcome_video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
