# Generated by Django 5.0.7 on 2024-07-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_gallerymodel_options_alter_homemodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='subtitle_banner_en',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='title_banner_en',
        ),
    ]
