# Generated by Django 5.0.7 on 2024-07-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homemodel_subtitle_banner_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='subtitle_banner_en',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='title_banner_en',
        ),
    ]
