# Generated by Django 5.0.7 on 2024-07-25 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('amount_of_people', models.IntegerField()),
                ('size', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('available', models.BooleanField()),
                ('slug', models.SlugField(editable=False, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_image', to='room.roommodel')),
            ],
        ),
    ]
