# Generated by Django 5.0.7 on 2024-07-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='size',
            field=models.IntegerField(verbose_name='Size in sq'),
        ),
    ]
