# Generated by Django 5.0.7 on 2024-07-26 01:02

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_roommodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
