# Generated by Django 5.0.7 on 2024-07-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_roommodel_created_roommodel_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommodel',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AddField(
            model_name='roommodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='description_es',
            field=models.TextField(null=True),
        ),
    ]
