# Generated by Django 5.0.7 on 2024-08-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_remove_roommodel_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='description_en',
            field=models.TextField(null=True),
        ),
    ]
